# Generated by Django 4.2.30 on 2026-04-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, help_text='卡片上显示的简短描述，留空则不显示', max_length=300, verbose_name='简介'),
        ),
    ]
